name:                massalia-migration
version:             0.1.0.0
github:              "theobat/massalia-migration"
license:             BSD3
author:              "Kanso"
maintainer:          "contact _ at _ kanso.ink"
copyright:           "2020 Kanso"

extra-source-files:
- README.rst
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web DB migration

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/massalia-migration#readme>

dependencies:
- base >= 4.7 && < 5
- protolude
- hasql
- hasql-migration
- hasql-transaction
- hasql-url
- uuid
- containers
- unordered-containers
- filepattern
- filepath
- bytestring
- text
- tasty
- tasty-hunit
- pretty-simple

library:
  source-dirs: src

tests:
  massalia-migration-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - massalia-migration
